server:
  port: 5050
  servlet:
    context-path: /spring-boot-features
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
